### ISSUE TITLE
Issue creating more than one user

### ISSUE THREAD

**Issue by SukhmeetSingh2002** [cdpc-iitrpr/cdpc-recruiter-backend#4]
> psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "api_user_username_key"
DETAIL:  Key (username)=() already exists.

Screenshot of the table 

![image](https://github.com/cdpc-iitrpr/cdpc-recruiter-backend/assets/78161187/d7a7159b-dd04-4f39-8067-fb52342037e9)

**Comment by khan-shahnawaz** [comment]
Thanks for highlighting this issue @SukhmeetSingh2002. This is happening because we are not setting username during signup and django is storing it as empty string by default. @akshat1712 has already fixed this by setting username to email(to ensure uniqueness).
Changes will be live soon.
